Organizations:

    - &Daisycon
        Name: Daisycon
        ID: OrdererMSP
        MSPDir: generated/crypto-material/ordererOrganizations/daisycon.sbc.andreasfurster.nl/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('OrdererMSP.admin')"
        OrdererEndpoints:
            - orderer0.daisycon.sbc.andreasfurster.nl:7050

    - &Coolblue
        Name: Coolblue
        ID: CoolblueMSP
        MSPDir: generated/crypto-material/peerOrganizations/coolblue.sbc.andreasfurster.nl/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('CoolblueMSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('CoolblueMSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('CoolblueMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('CoolblueMSP.member')"
        AnchorPeers:
            - Host: peer0.coolblue.sbc.andreasfurster.nl
              Port: 7051

    - &Tweakers
        Name: Tweakers
        ID: TweakersMSP
        MSPDir: generated/crypto-material/peerOrganizations/tweakers.sbc.andreasfurster.nl/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('TweakersMSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('TweakersMSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('TweakersMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('TweakersMSP.member')"
        AnchorPeers:
            - Host: peer0.tweakers.sbc.andreasfurster.nl
              Port: 8051

Capabilities:
    Channel: &ChannelCapabilities
        V2_0: true
    Orderer: &OrdererCapabilities
        V2_0: true
    Application: &ApplicationCapabilities
        V2_0: true

Application: &ApplicationDefaults
    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        LifecycleEndorsement:
            Type: ImplicitMeta
            Rule: "ANY Endorsement"
        Endorsement:
            Type: ImplicitMeta
            Rule: "ANY Endorsement"
    Capabilities:
        <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
    OrdererType: etcdraft
    EtcdRaft:
        Consenters:
        - Host: orderer0.daisycon.sbc.andreasfurster.nl
          Port: 7050
          ClientTLSCert: generated/crypto-material/ordererOrganizations/daisycon.sbc.andreasfurster.nl/orderers/orderer0.daisycon.sbc.andreasfurster.nl/tls/server.crt
          ServerTLSCert: generated/crypto-material/ordererOrganizations/daisycon.sbc.andreasfurster.nl/orderers/orderer0.daisycon.sbc.andreasfurster.nl/tls/server.crt
    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB
    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"

Channel: &ChannelDefaults
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
    Capabilities:
        <<: *ChannelCapabilities

Profiles:
    ApNetworkProfile:
        <<: *ChannelDefaults
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *Daisycon
            Capabilities:
                <<: *OrdererCapabilities
        Consortiums:
            ApConsortium:
                Organizations:
                    - *Coolblue
                    - *Tweakers
    ApChannelProfile:
        Consortium: ApConsortium
        <<: *ChannelDefaults
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Coolblue
                - *Tweakers
            Capabilities:
                <<: *ApplicationCapabilities
